module.exports = class Exercise {
  constructor() {
    this.COEFFICIENT_FOR_STRENGTH = 0.87;
    this.NUMBER_OF_REPETITION_FOR_STRENGTH = 5;
    this.COEFFICIENT_FOR_HYPERTROPHY = 0.8;
    this.NUMBER_OF_REPETITION_FOR_HYPERTROPHY = 8;
    this.COEFFICIENT_FOR_ENDURANCE = 0.65;
    this.NUMBER_OF_REPETITION_FOR_ENDURANCE = 18;
    this.NUMBER_OF_SETS = 3;
  }
};
